# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: stellaris-insights

builds:
- main: ctl/main.go
  goos:
    - linux
    - darwin
    - windows

archive:
  wrap_in_directory: stellaris-insights
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: osx
    386: i386
    amd64: x86_64

sign:
  artifacts: all
  args: ["-u", "19BDD98D4C905E242D38909899954537626AFDA0", "--output", "${signature}", "--detach-sign", "${artifact}"]

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  draft: true
  github:
    owner: stellaris-insights
    name: uploader