// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import fsnotify "github.com/fsnotify/fsnotify"

import mock "github.com/stretchr/testify/mock"

// FSNotifier is an autogenerated mock type for the FSNotifier type
type FSNotifier struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *FSNotifier) Add(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *FSNotifier) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Errors provides a mock function with given fields:
func (_m *FSNotifier) Errors() chan error {
	ret := _m.Called()

	var r0 chan error
	if rf, ok := ret.Get(0).(func() chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan error)
		}
	}

	return r0
}

// Events provides a mock function with given fields:
func (_m *FSNotifier) Events() chan fsnotify.Event {
	ret := _m.Called()

	var r0 chan fsnotify.Event
	if rf, ok := ret.Get(0).(func() chan fsnotify.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan fsnotify.Event)
		}
	}

	return r0
}

// Remove provides a mock function with given fields: _a0
func (_m *FSNotifier) Remove(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
